### ISSUE TITLE
Question - Swiping Previous / next

### ISSUE THREAD

**Issue by theunreal** [dragonza/swipe-demo#1]
It's not a real issue, Just curious:

I was trying to change this code and make a swipe right move to the next item while swiping the left move to the previous item.
To do this, I had to move the index state to the parent component, and it worked, using the following method:

```
handleLikedJob = () => {
    const { index } = this.state;
    const updateIndex = index + 1 === jobs.length ? 0 : index + 1;

    this.setState({
      index: updateIndex,
    });
  };

  handlePassedJob = () => {
    const { index } = this.state;
    const updateIndex = index - 1 === -1 ? jobs.length - 1 : index - 1;

    this.setState({
      index: updateIndex,
    });
  };
```

The issue is, when swiping from the first item back / the last item next - the rendering of the card below doesn't work well. The animation is not working as expected.

Any idea how to solve it?

Thanks!

**Comment by dragonza** [comment]
Hi,
from what I understand is that you want your deck of card to loop over the same deck when they are at the first item / last item. Is that what you would like to achieve?

In that case you have to look here https://github.com/dragonza/swipe-demo/blob/master/Swipe.js#L93 to change the renderCard logic to make it rerender the deck when it is at last/first items.
